-- =============================================================
-- 0017: 確認待ちの記憶候補を、30日で自動的に期限切れにする（Phase B ／ G4）
--
-- 【なにが問題だったか】
-- 期限切れの処理は、本人が画面を開いたときにだけ動いていた。
-- 本人が使わなくなると、30日を過ぎた候補の本文と「AIが候補にした理由」が
-- いつまでも残っていた。
--
-- 【この migration ですること】
-- ① 期限処理の関数を作る（画面からは呼べない）
-- ② 動いた記録の表を作る（本文・利用者・候補の番号は持たない）
-- ③ Supabase の定期実行（pg_cron）で、毎日1回（日本時間 3:15 ごろ）動かす
-- ④ 定期実行の仕組み自体の記録（cron.job_run_details）も、7日より前の分を毎日消す
--
-- 画面を開いたときの期限処理（actions.ts の expireOldCandidates）は、予備として残す。
-- どちらが先に動いても、先に閉じた方だけが1回書き換える（あとの方は0件）。
--
-- 【鍵を増やさない】
-- DB の中で完結する。アプリにも Vercel にも、新しい鍵は要らない。
-- =============================================================

-- -------------------------------------------------------------
-- 1. 定期実行の機能を有効にする（Supabase の公式の手順）
-- -------------------------------------------------------------
create extension if not exists pg_cron with schema pg_catalog;

grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

-- -------------------------------------------------------------
-- 2. 動いた記録
--
-- 残すのは「どの処理が・いつ・何件・うまくいったか」だけ。
-- 本文・利用者の番号・候補の番号は持たない。
-- 失敗したときに残すのは、DB のエラーの番号（5文字）だけ（エラー文は残さない）。
-- 90日より前の行は、期限処理のたびに消す。
-- -------------------------------------------------------------
create table public.maintenance_runs (
  -- 番号は by default（バックアップから戻すとき、控えの番号のまま入れ直せるように）
  id bigint generated by default as identity primary key,
  job text not null check (job in ('expire_candidates')),
  ran_at timestamptz not null default now(),
  affected integer not null default 0,
  ok boolean not null,
  -- 失敗したときの DB のエラーの番号（例 40P01）。成功なら null
  error_code text check (error_code is null or error_code ~ '^[0-9A-Z]{5}$')
);

comment on table public.maintenance_runs is
  '自動の処理が動いた記録。処理の名前・日時・件数・成否だけ。本文・利用者・候補の番号は持たない。90日で消す。';

create index maintenance_runs_job_idx on public.maintenance_runs (job, ran_at desc);

alter table public.maintenance_runs enable row level security;
-- ポリシーは作らない ＝ 本人（authenticated）も未ログイン（anon）も読めない・書けない。
-- 読むのは運営の点検コマンド（Supabase CLI）とテスト（service_role）だけ。
grant all on table public.maintenance_runs to service_role;

-- -------------------------------------------------------------
-- 3. 期限処理
--
-- 対象：状態が「確認待ち」で、期限（作成から30日。expires_at）を過ぎたものだけ。
-- 処理：状態を「期限切れ」にし、本文と「AIが候補にした理由」を消す
--       （画面の予備の処理と同じ内容。番号・日時・由来などは残す）。
-- 何度続けて動かしても安全（2回目は0件）。
--
-- 全利用者の行を扱うので、画面（authenticated / anon）からは呼べない。
-- 呼べるのは、定期実行（postgres）とテスト（service_role）だけ。
-- 返すのは件数だけ（失敗したときは -1）。
-- -------------------------------------------------------------
create function public.expire_pending_candidates()
  returns integer
  language plpgsql
  set search_path = public
as $$
declare
  n integer := 0;
begin
  begin
    update public.memory_candidates
    set status = 'expired',
        suggested_text = null,
        confirmed_text = null,
        extraction_reason = null
    where status = 'pending'
      and expires_at <= now();
    get diagnostics n = row_count;

    insert into public.maintenance_runs (job, affected, ok)
    values ('expire_candidates', n, true);
  exception when others then
    /* 失敗しても、失敗したことだけは残す（上の書き換えは取り消される）。
       エラー文には値が入ることがあるので、番号（SQLSTATE）だけを残す。 */
    insert into public.maintenance_runs (job, affected, ok, error_code)
    values ('expire_candidates', 0, false, sqlstate);
    n := -1;
  end;

  -- 90日より前の記録を消す
  delete from public.maintenance_runs
  where ran_at < now() - interval '90 days';

  return n;
end;
$$;

comment on function public.expire_pending_candidates() is
  '30日を過ぎた確認待ちの候補を期限切れにし、本文と理由を消す。件数を返す（失敗は -1）。画面からは呼べない。';

revoke all on function public.expire_pending_candidates() from public;
revoke all on function public.expire_pending_candidates() from anon, authenticated;
grant execute on function public.expire_pending_candidates() to service_role;

-- -------------------------------------------------------------
-- 4. 毎日の予定（時刻は世界標準時。日本時間 = +9時間）
--
-- 同じ名前で登録し直すと、上書きになる（何度 migration を当てても1つだけ）。
-- -------------------------------------------------------------

-- 期限処理：毎日 18:15（日本時間 3:15）
select cron.schedule(
  'ai-kasshi-expire-candidates',
  '15 18 * * *',
  $$select public.expire_pending_candidates()$$
);

-- 定期実行の仕組み自体の記録を、7日より前の分だけ消す：毎日 18:30（日本時間 3:30）
-- （Supabase の公式の手順どおり。消さないと増え続ける）
select cron.schedule(
  'ai-kasshi-cron-history-cleanup',
  '30 18 * * *',
  $$delete from cron.job_run_details where end_time < now() - interval '7 days'$$
);
